{
    "msg_1": {
        "content": "NMI watchdog: Perf event create on CPU 0 failed with -2",
        "analyze": "No such file or directory, it maybe expected as cpu not support",
        "branch": "rhel8",
        "status": "active",
        "link": "",
        "path": "dmesg or journal",
        "trigger": ""
    },
    "msg_2": {
        "content": "acpi PNP0A03:00: fail to add MMCONFIG information, can't access extended PCI configuration space under this bridge.",
        "analyze": "The messages in question indicate that OS is disabling ASPM as the BIOS doesn't support ASPM.d",
        "branch": "rhel7,rhel8",
        "status": "active",
        "link": "https://access.redhat.com/solutions/4057221",
        "path": "dmesg or journal",
        "trigger": ""
    },
    "msg_3": {
        "content": "acpi PNP0A03:00: _OSC failed (AE_NOT_FOUND); disabling ASPM",
        "analyze": "The messages in question indicate that OS is disabling ASPM as the BIOS doesn't support ASPM.",
        "branch": "rhel7,rhel8",
        "status": "active",
        "link": "https://access.redhat.com/solutions/4057221",
        "path": "dmesg or journal",
        "trigger": ""
    },
    "msg_4": {
        "content": "systemd[1]: Failed to insert module 'ip_tables': Operation not permitted",
        "analyze": "Known issue",
        "branch": "rhel8",
        "status": "inactive",
        "link": "https://bugzilla.redhat.com/show_bug.cgi?id=1600903",
        "path": "dmesg or journal",
        "trigger": ""
    },
    "msg_5": {
        "content": "RAS: Correctable Errors collector initialized.",
        "analyze": "It is only a information with error keyword",
        "branch": "rhel8",
        "status": "active",
        "link": "",
        "path": "dmesg or journal",
        "trigger": ""
    },
    "msg_6": {
        "content": "i8042: Warning: Keylock active",
        "analyze": "It is mostly like a warning without any function impact, same in Amazon Linux 2",
        "branch": "rhel7,rhel8,rhel9",
        "status": "active",
        "link": "",
        "path": "dmesg or journal",
        "trigger": ""
    },
    "msg_7": {
        "content": "random: 7 urandom warning(s) missed due to ratelimiting",
        "analyze": "Frequently seeing, no ec2 specified",
        "branch": "rhel8",
        "status": "active",
        "link": "",
        "path": "dmesg or journal",
        "trigger": ""
    },
    "msg_9": {
        "content": "nvmet: failed to open block device /home/ec2-user/blktests/results/tmpdir.nvme.028.NcS/img: (-15)",
        "analyze": "blktests generated",
        "branch": "rhel7,rhel8",
        "status": "active",
        "link": "",
        "path": "dmesg or journal",
        "trigger": ""
    },
    "msg_10": {
        "content": "ena 0000:00:05.0: Elastic Network Adapter (ENA) v2.0.2K",
        "analyze": "ena msg",
        "branch": "rhel7,rhel8",
        "status": "active",
        "link": "",
        "path": "dmesg or journal",
        "trigger": ""
    },
    "msg_11": {
        "content": "ena: ena device version: 0.10",
        "analyze": "ena msg",
        "branch": "rhel7,rhel8",
        "status": "active",
        "link": "",
        "path": "dmesg or journal",
        "trigger": ""
    },
    "msg_12": {
        "content": "ena: ena controller version: 0.0.1 implementation version 1",
        "analyze": "ena msg",
        "branch": "rhel7,rhel8",
        "status": "active",
        "link": "",
        "path": "dmesg or journal",
        "trigger": ""
    },
    "msg_13": {
        "content": "ena 0000:00:05.0: creating 8 io queues. queue size: 1024. LLQ is ENABLED",
        "analyze": "ena msg",
        "branch": "rhel7,rhel8",
        "status": "active",
        "link": "",
        "path": "dmesg or journal",
        "trigger": ""
    },
    "msg_14": {
        "content": "ena 0000:00:05.0: Elastic Network Adapter (ENA) found at mem febf4000, mac addr 0a:6c:ef:80:b2:be Queues 8, Placement policy: Low Latency",
        "analyze": "ena msg",
        "branch": "rhel7,rhel8",
        "status": "active",
        "link": "",
        "path": "dmesg or journal",
        "trigger": ""
    },
    "msg_15": {
        "content": "ena 0000:00:05.0: enabling device (0010 -> 0012)",
        "analyze": "ena arm msg",
        "branch": "rhel7,rhel8",
        "status": "active",
        "link": "",
        "path": "dmesg or journal",
        "trigger": ""
    },
    "msg_16": {
        "content": ".*NUMA: Failed to initialise from firmware.*",
        "analyze": "this happens in non-metal arm instance only, eg. aws,hyper-v,esxi",
        "branch": "rhel",
        "status": "active",
        "link": "",
        "path": "journal, dmesg",
        "trigger": "HYP mode not available"
    },
    "msg_17": {
        "content": "ena 0000:00:05.0: irq 45 for MSI/MSI-X",
        "analyze": "ena message in i3en.6xlarge",
        "branch": "rhel7,rhel8",
        "status": "active",
        "link": "",
        "path": "dmesg or journal",
        "trigger": ""
    },
    "msg_18": {
        "content": "ERST: Error Record Serialization Table (ERST) support is initialized.",
        "analyze": "information only",
        "branch": "rhel7",
        "status": "active",
        "link": "",
        "path": "dmesg or journal",
        "trigger": ""
    },
    "msg_19": {
        "content": "ena 0000:00:05.0: LLQ is not supported Fallback to host mode policy.",
        "analyze": "t3",
        "branch": "rhel7,rhel8",
        "status": "active",
        "link": "",
        "path": "dmesg or journal",
        "trigger": ""
    },
    "msg_20": {
        "content": "pci 0000:00:02.0: BAR 13: failed to assign [io  size 0x10000]",
        "analyze": "appears in bare metal instance or esx platform, no functional impact",
        "branch": "rhel7,rhel8",
        "status": "active",
        "link": "https://access.redhat.com/solutions/3144711",
        "path": "dmesg or journal",
        "trigger": ""
    },
    "msg_21": {
        "content": "ipmi_si dmi-ipmi-si.0: Interface detection failed",
        "analyze": "appears in bare metal instance",
        "branch": "rhel7,rhel8",
        "status": "active",
        "link": "https://bugzilla.redhat.com/show_bug.cgi?id=1538887",
        "path": "dmesg or journal",
        "trigger": "amazon"
    },
    "msg_22": {
        "content": "ena 0002:04:00.0: Adding to iommu group 53",
        "analyze": "appears in arm bare metal instance",
        "branch": "rhel7,rhel8",
        "status": "active",
        "link": "",
        "path": "dmesg or journal",
        "trigger": ""
    },
    "msg_23": {
        "content": "ena 0002:04:00.0: Linked as a consumer to arm-smmu.0.auto",
        "analyze": "appears in arm bare metal instance",
        "branch": "rhel7,rhel8",
        "status": "active",
        "link": "",
        "path": "dmesg or journal",
        "trigger": ""
    },
    "msg_24": {
        "content": "BERT: Boot Error Record Table support is disabled. Enable it by using bert_enable as kernel parameter.",
        "analyze": "information only",
        "branch": "rhel7",
        "status": "active",
        "link": "",
        "path": "dmesg or journal",
        "trigger": ""
    },
    "msg_25": {
        "content": "arm_spe_pmu arm,spe-v1: profiling buffer inaccessible. Try passing  kpti=off  on the kernel command line",
        "analyze": "information only, manually set and pass",
        "branch": "rhel8",
        "status": "active",
        "link": "",
        "path": "dmesg or journal",
        "trigger": ""
    },
    "msg_26": {
        "content": "arm_spe_pmu: probe of arm,spe-v1 failed with error -1",
        "analyze": "information only, manually set and pass",
        "branch": "rhel8",
        "status": "active",
        "link": "",
        "path": "dmesg or journal",
        "trigger": ""
    },
    "msg_27": {
        "content": "mcelog[873]: mcelog: ERROR: AMD Processor family 21: mcelog does not support this processor.  Please use the edac_mce_amd module instead.",
        "analyze": "information only",
        "branch": "rhel8",
        "status": "active",
        "link": "",
        "path": "dmesg or journal",
        "trigger": ""
    },
    "msg_28": {
        "content": "kdumpctl[1108]: Warning: There might not be enough space to save a vmcore.",
        "analyze": "information only",
        "branch": "rhel8,rhel7",
        "status": "active",
        "link": "",
        "path": "dmesg or journal",
        "trigger": ""
    },
    "msg_29": {
        "content": "augenrules[681]: failure 1",
        "analyze": "information only",
        "branch": "rhel8,rhel7",
        "status": "active",
        "link": "https://access.redhat.com/solutions/3343401",
        "path": "journal",
        "trigger": ""
    },
    "msg_30": {
        "content": "dbus-daemon[767]: [system] Activation via systemd failed for unit 'dbus-org.freedesktop.resolve1.service': Unit dbus-org.freedesktop.resolve1.service not found.",
        "analyze": "information only",
        "branch": "rhel8,rhel7",
        "status": "active",
        "link": "https://bugzilla.redhat.com/show_bug.cgi?id=1855252",
        "path": "journal",
        "trigger": ""
    },
    "msg_31": {
        "content": "systemd-vconsole-setup[316]: KD_FONT_OP_GET failed while trying to get the font metadata: Function not implemented",
        "analyze": "know bug before RHEL-8.4",
        "branch": "rhel8.4-",
        "status": "active",
        "link": "https://access.redhat.com/solutions/4907991",
        "path": "journal",
        "trigger": ""
    },
    "msg_32": {
        "content": "rngd[780]: Failed to init entropy source hwrng",
        "analyze": "Expected if no hwrng device present, cat /dev/hwrng, /sys/devices/virtual/misc/hw_random/rng_available",
        "branch": "rhel7,rhel8",
        "status": "active",
        "link": "https://bugzilla.redhat.com/show_bug.cgi?id=1679010",
        "path": "journal",
        "trigger": ""
    },
    "msg_33": {
        "content": "sshd[5433]: error: kex_exchange_identification: banner line contains invalid characters",
        "analyze": "Maybe triggered by some scan software, will research more",
        "branch": "rhel7,rhel8",
        "status": "active",
        "link": "",
        "path": "journal",
        "trigger": ""
    },
    "msg_34": {
        "content": "sshd[5433]: error: send_error: write: Connection reset by peer",
        "analyze": "Maybe triggered by some scan software, will research more",
        "branch": "rhel7,rhel8",
        "status": "active",
        "link": "",
        "path": "journal",
        "trigger": ""
    },
    "msg_35": {
        "content": "dbus-daemon[8161]: [system] Failed to reset fd limit before activating service: org.freedesktop.DBus.Error.AccessDenied: Failed to restore old fd limit: Operation not permitted",
        "analyze": "Known issue",
        "branch": "rhel8",
        "status": "active",
        "link": "https://bugzilla.redhat.com/show_bug.cgi?id=1839753",
        "path": "journal",
        "trigger": ""
    },
    "msg_36": {
        "content": "WARNING, didn't collect load info for all cpus, balancing is broken",
        "analyze": "Usually triggered by cpuhotplug test",
        "branch": "rhel8",
        "status": "active",
        "link": "",
        "path": "journal",
        "trigger": "cpuhotplug"
    },
    "msg_37": {
        "content": "gnome-shell[1682]: Getting invalid resource scale property",
        "analyze": "Information only",
        "branch": "rhel8",
        "status": "active",
        "link": "",
        "path": "journal",
        "trigger": ""
    },
    "msg_38": {
        "content": "systemd[1]: /usr/lib/systemd/system/systemd-resolved.service:33: Unknown lvalue 'ProtectSystems' in section 'Service'",
        "analyze": "Known bug",
        "branch": "rhel8.3",
        "status": "active",
        "link": "https://bugzilla.redhat.com/show_bug.cgi?id=1871139",
        "path": "journal",
        "trigger": ""
    },
    "msg_39": {
        "content": "crond[1100]: (root) FAILED (loading cron table)",
        "analyze": "Known bug",
        "branch": "rhel8.3",
        "status": "active",
        "link": "https://bugzilla.redhat.com/show_bug.cgi?id=1879368",
        "path": "journal",
        "trigger": ""
    },
    "msg_40": {
        "content": "psmouse serio1: trackpoint: failed to get extended button data, assuming 3 buttons",
        "analyze": "It is a harmless message. You can ignore it.",
        "branch": "rhel",
        "status": "active",
        "link": "https://access.redhat.com/solutions/2023283",
        "path": "dmesg",
        "trigger": ""
    },
    "msg_41": {
        "content": "org.gnome.Shell.desktop[1578]: libEGL warning: DRI2: failed to create dri screen",
        "analyze": "Known issue",
        "branch": "rhel",
        "status": "active",
        "link": "https://bugzilla.redhat.com/show_bug.cgi?id=1877997",
        "path": "journal",
        "trigger": ""
    },
    "msg_42": {
        "content": "gnome-shell[1578]: Failed to initialize accelerated iGPU/dGPU framebuffer sharing: Do not want to use software renderer (llvmpipe (LLVM 10.0.1, 256 bits)), falling back to CPU copy path",
        "analyze": "Known issue",
        "branch": "rhel",
        "status": "active",
        "link": "https://bugzilla.redhat.com/show_bug.cgi?id=1877997",
        "path": "journal",
        "trigger": ""
    },
    "msg_43": {
        "content": "gnome-shell[1578]: Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation",
        "analyze": "This message appears when GNOME location services is disabled. This message can be safely ignored.",
        "branch": "rhel",
        "status": "active",
        "link": "https://access.redhat.com/solutions/4831511",
        "path": "journal",
        "trigger": ""
    },
    "msg_44": {
        "content": "org.gnome.Shell.desktop[1578]: Errors from xkbcomp are not fatal to the X server",
        "analyze": "Known bug.",
        "branch": "rhel",
        "status": "active",
        "link": "https://bugzilla.redhat.com/show_bug.cgi?id=1780463",
        "path": "journal",
        "trigger": ""
    },
    "msg_45": {
        "content": "org.gnome.Shell.desktop[1578]: > Warning:          Could not resolve keysym XF86MonBrightnessCycle",
        "analyze": "Known issue",
        "branch": "rhel",
        "status": "active",
        "link": "https://bugzilla.redhat.com/show_bug.cgi?id=1780463",
        "path": "journal",
        "trigger": ""
    },
    "msg_46": {
        "content": "gnome-shell[1578]: JS WARNING: [resource:///org/gnome/shell/ui/windowManager.js 1643]: reference to undefined property 'MetaWindowXwayland'",
        "analyze": "This warning is harmless",
        "branch": "rhel",
        "status": "active",
        "link": "https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/1314",
        "path": "journal",
        "trigger": ""
    },
    "msg_47": {
        "content": "org.gnome.Shell.desktop[1578]: Failed to initialize glamor, falling back to sw",
        "analyze": "I think this warning is harmless because exists on other platform too. eg. 1730315",
        "branch": "rhel",
        "status": "active",
        "link": "",
        "path": "journal",
        "trigger": "Missing Wayland requirements for glamor"
    },
    "msg_48": {
        "content": "colord[1817]: failed to get edid data: EDID length is too small",
        "analyze": "It may not a bug.",
        "branch": "rhel",
        "status": "active",
        "link": "https://bugzilla.redhat.com/show_bug.cgi?id=1368291",
        "path": "journal",
        "trigger": ""
    },
    "msg_49": {
        "content": "gsd-color[1745]: failed to get edid: unable to get EDID for output",
        "analyze": "Wont fix bug.",
        "branch": "rhel",
        "status": "active",
        "link": "https://bugzilla.redhat.com/show_bug.cgi?id=1332997",
        "path": "journal",
        "trigger": "EDID length is too small"
    },
    "msg_50": {
        "content": "sshd[1621]: reverse mapping checking getaddrinfo for nat-pool-xxx.xxx.redhat.com [00.000.000.000] failed - POSSIBLE BREAK-IN ATTEMPT!",
        "analyze": "There is (most likely) no 'attack' occurring when this message is displayed.",
        "branch": "rhel",
        "status": "active",
        "link": "https://access.redhat.com/solutions/83933",
        "path": "journal",
        "trigger": ""
    },
    "msg_51": {
        "content": "kernel: CPU features: detected: Instruction cache invalidation not required for I/D coherence",
        "analyze": "Information only",
        "branch": "rhel",
        "status": "active",
        "link": "",
        "path": "journal",
        "trigger": ""
    },
    "msg_52": {
        "content": "kernel: DMAR-IR: Queued invalidation will be enabled to support x2apic and Intr-remapping.;.*Using Queued invalidation.*",
        "analyze": "Feature enabled, RFEBZ 1358653",
        "branch": "rhel",
        "status": "active",
        "link": "",
        "path": "journal or dmesg",
        "trigger": ""
    },
    "msg_53": {
        "content": "iscsid[466]: iscsid: Warning: InitiatorName file /etc/iscsi/initiatorname.iscsi does not exist or does not contain a properly formatted InitiatorName. If using software iscsi (iscsi_tcp or ib_iser) or partial offload (bnx2i or cxgbi iscsi), you may not be able to log into or discover targets. Please create a file /etc/iscsi/initiatorname.iscsi that contains a sting with the format: InitiatorName=iqn.yyyy-mm.<reversed domain name>[:identifier].",
        "analyze": "Known bug.",
        "branch": "rhel8",
        "status": "active",
        "link": "https://bugzilla.redhat.com/show_bug.cgi?id=1882913",
        "path": "journal",
        "trigger": ""
    },
    "msg_54": {
        "content": "iTCO_wdt: unable to reset NO_REBOOT flag, device disabled by hardware/BIOS",
        "analyze": "Information only.",
        "branch": "rhel",
        "status": "active",
        "link": "https://access.redhat.com/solutions/39240",
        "path": "dmesg",
        "trigger": ""
    },
    "msg_55": {
        "content": "ghes_edac: Its SMBIOS info is wrong. It is doubtful that the error report would",
        "analyze": "Kown bug and wait aws update.",
        "branch": "rhel",
        "status": "active",
        "link": "https://bugzilla.redhat.com/show_bug.cgi?id=1836065",
        "path": "dmesg or journal",
        "trigger": ""
    },
    "msg_56": {
        "content": "/usr/sbin/irqbalance[1698]: GUESSING AARCH64 CLASS FOR arm-smmu-v3-gerror",
        "analyze": "Information only",
        "branch": "rhel",
        "status": "active",
        "link": "",
        "path": "journal",
        "trigger": ""
    },
    "msg_57": {
        "content": "eth0: Invalid MTU 127 requested, hw min 128",
        "analyze": "Maybe generated by test_mtu_min_max_set",
        "branch": "rhel",
        "status": "active",
        "link": "",
        "path": "journal or dmesg",
        "trigger": "os_tests.tests.test_network_test.TestNetworkTest.test_mtu_min_max_set"
    },
    "msg_58": {
        "content": "libvirtd[43301]: internal error: Invalid unsigned integer value '-1' in file '/sys/devices/system/cpu/cpu0/topology/die_id'",
        "analyze": "Know issue in arm bz#1876742",
        "branch": "rhel8",
        "status": "active",
        "link": "https://bugzilla.redhat.com/show_bug.cgi?id=1876742",
        "path": "journal",
        "trigger": ""
    },
    "msg_59": {
        "content": "kernel: hub 2-0:1.0: config failed, hub doesn't have any ports! (err -19)",
        "analyze": "Know fail log in kernel, patch is not implemented yet",
        "branch": "rhel8",
        "status": "active",
        "link": "https://lore.kernel.org/patchwork/patch/863993/",
        "path": "journal",
        "trigger": ""
    },
    "msg_60": {
        "content": "kernel: DMAR: dmar6: Using Queued invalidation",
        "analyze": "Information only in iommu",
        "branch": "rhel",
        "status": "active",
        "link": "",
        "path": "journal",
        "trigger": "intel_iommu=on"
    },
    "msg_61": {
        "content": "sshd[4419]: error: kex_exchange_identification: Connection closed by remote host",
        "analyze": "Maybe triggered by some scan software or earlier login failure, will research more",
        "branch": "rhel7,rhel8",
        "status": "active",
        "link": "",
        "path": "journal",
        "trigger": ""
    },
    "msg_62": {
        "content": "kernel: SGI XFS with ACLs, security attributes, verbose warnings, no debug enabled",
        "analyze": "debug kernel information only",
        "branch": "rhel7,rhel8",
        "status": "active",
        "link": "",
        "path": "journal",
        "trigger": ""
    },
    "msg_63": {
        "content": "dnf[4394]: Failed determining last makecache time.",
        "analyze": "happens at first time boot, should disappear after reboot",
        "branch": "rhel7,rhel8",
        "status": "active",
        "link": "",
        "path": "journal",
        "trigger": "Metadata cache created."
    },
    "msg_64": {
        "content": "kernel: SGI XFS with ACLs, security attributes, verbose warnings, no debug enabled",
        "analyze": "information only in debug kernel",
        "branch": "rhel7,rhel8",
        "status": "active",
        "link": "",
        "path": "journal, dmesg",
        "trigger": ""
    },
    "msg_65": {
        "content": "kernel: Invalid max_queues (4), will use default max: 2.",
        "analyze": "xen_blkif_max_queues > online nr_cpus",
        "branch": "rhel",
        "status": "active",
        "link": "",
        "path": "journal, dmesg",
        "trigger": "Xen HVM domU"
    },
    "msg_66": {
        "content": "insights-client[1133]: Error: Could not submit event: Could not find the TLS certificate file, invalid path: /etc/pki/consumer/cert.pem",
        "analyze": "known issue",
        "branch": "rhel",
        "status": "active",
        "link": "https://bugzilla.redhat.com/show_bug.cgi?id=1907266",
        "path": "journal, dmesg",
        "trigger": ""
    },
    "msg_67": {
        "content": "sshd[7714]: error: maximum authentication attempts exceeded for root from 75.165.202.153 port 51082 ssh2 [preauth]",
        "analyze": "information only when not allowed user try to access our system",
        "branch": "rhel",
        "status": "active",
        "link": "",
        "path": "journal, dmesg",
        "trigger": "Too many authentication failures"
    },
    "msg_68": {
        "content": "sshd[6899]: Disconnecting invalid user admin 184.102.37.82 port 32770: Too many authentication failures [preauth]",
        "analyze": "information only when not allowed user try to access our system",
        "branch": "rhel",
        "status": "active",
        "link": "",
        "path": "journal, dmesg",
        "trigger": "Too many authentication failures"
    },
    "msg_69": {
        "content": "avahi-daemon[908]: WARNING: No NSS support for mDNS detected, consider installing nss-mdns!",
        "analyze": "It's not a bug, just a warning to indicate that the libs supporting for mDNS are not installed in Red Hat Enterprise Linux.",
        "branch": "rhel",
        "status": "active",
        "link": "https://access.redhat.com/solutions/18783",
        "path": "journal, dmesg",
        "trigger": ""
    },
    "msg_70": {
        "content": "systemd[1]: mcelog.service: Main process exited, code=exited, status=1/FAILURE",
        "analyze": "Information only on unsupported cpu.",
        "branch": "rhel",
        "status": "active",
        "link": "",
        "path": "journal, dmesg",
        "trigger": "mcelog does not support this processor"
    },
    "msg_71": {
        "content": ".*systemd[1]: mcelog.service: Failed with result 'exit-code'.*",
        "analyze": "Information only on unsupported cpu.",
        "branch": "rhel",
        "status": "active",
        "link": "",
        "path": "journal, dmesg",
        "trigger": "mcelog does not support this processor"
    },
    "msg_72": {
        "content": "lvm[761]:   Failed to get primary device for 259:1.",
        "analyze": "known issue",
        "branch": "rhel8",
        "status": "active",
        "link": "https://bugzilla.redhat.com/show_bug.cgi?id=1925871",
        "path": "journal, dmesg",
        "trigger": "blob data"
    },
    "msg_73": {
        "content": "lvm[761]:   readlink failed: Invalid argument",
        "analyze": "known issue",
        "branch": "rhel8",
        "status": "active",
        "link": "https://bugzilla.redhat.com/show_bug.cgi?id=1925871",
        "path": "journal, dmesg",
        "trigger": "blob data"
    },
    "msg_74": {
        "content": "insights-client[1876]: Error: failed to download advisor report.",
        "analyze": "known issue",
        "branch": "rhel",
        "status": "active",
        "link": "https://bugzilla.redhat.com/show_bug.cgi?id=1907266",
        "path": "journal, dmesg",
        "trigger": "Could not find the TLS certificate file"
    },
    "msg_75": {
        "content": "smpboot: do_boot_cpu failed(-1) to wakeup CPU#0",
        "analyze": "known issue",
        "branch": "rhel",
        "status": "active",
        "link": "https://bugzilla.redhat.com/show_bug.cgi?id=1929266",
        "path": "journal, dmesg",
        "trigger": "starting cpuhotplug"
    },
    "msg_76": {
        "content": "usr/sbin/era_invalidate -> pdata_tools",
        "analyze": "this is a tool name instead of a actual invalid",
        "branch": "rhel",
        "status": "active",
        "link": "",
        "path": "journal, dmesg",
        "trigger": ""
    },
    "msg_77": {
        "content": "kernel: blk_update_request: operation not supported error, dev loop0, sector 524160 op 0x9:(WRITE_ZEROES) flags 0x800800 phys_seg 0 prio class 0",
        "analyze": "this is a low priority warning during ltp test, will investigate later",
        "branch": "rhel9",
        "status": "active",
        "link": "",
        "path": "journal, dmesg",
        "trigger": "LTP: starting fsync01"
    },
    "msg_78": {
        "content": "integrity: Unable to open file: /etc/keys/x509_ima.der (-2)",
        "analyze": "this is not a RHEL specific problem and looks like not a real error",
        "branch": "rhel9",
        "status": "active",
        "link": "https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1771555",
        "path": "journal, dmesg",
        "trigger": ""
    },
    "msg_79": {
        "content": "usr/lib/kbd/consolefonts/ERRORS",
        "analyze": "this is an information only",
        "branch": "rhel",
        "status": "active",
        "link": "",
        "path": "journal, dmesg",
        "trigger": ""
    },
    "msg_80": {
        "content": "usr/lib64/libgpg-error.so.0 -> ../../lib64/libgpg-error.so.0.32.0",
        "analyze": "this is a mode name only",
        "branch": "rhel",
        "status": "active",
        "link": "",
        "path": "journal, dmesg",
        "trigger": ""
    },
    "msg_81": {
        "content": "usr/lib64/libgpg-error.so.0.32.0",
        "analyze": "this is a mode name only",
        "branch": "rhel",
        "status": "active",
        "link": "",
        "path": "journal, dmesg",
        "trigger": ""
    },
    "msg_82": {
        "content": "COMMAND=/usr/bin/systemd-analyze verify systemd-boot-check-no-failures.service",
        "analyze": "this is a service name only",
        "branch": "rhel",
        "status": "active",
        "link": "",
        "path": "journal, dmesg",
        "trigger": ""
    },
    "msg_83": {
        "content": "audit.* res=failed",
        "analyze": "audit fail information",
        "branch": "rhel",
        "status": "active",
        "link": "https://access.redhat.com/solutions/2050393",
        "path": "journal, dmesg",
        "trigger": ""
    },
    "msg_84": {
        "content": "network[820]: WARN      : [network] You are using 'network' service provided by 'network-scripts', which are now deprecated.",
        "analyze": "this is a warning info if you updated from 7.9 to 8.4 as network.service used",
        "branch": "rhel",
        "status": "active",
        "link": "",
        "path": "journal, dmesg",
        "trigger": ""
    },
    "msg_85": {
        "content": "network[820]: WARN      : [network] 'network-scripts' will be removed in one of the next major releases of RHEL.",
        "analyze": "this is a warning info if you updated from 7.9 to 8.4 as network.service used",
        "branch": "rhel",
        "status": "active",
        "link": "",
        "path": "journal, dmesg",
        "trigger": ""
    },
    "msg_86": {
        "content": "network[820]: WARN      : [network] It is advised to switch to 'NetworkManager' instead for network management.",
        "analyze": "this is a warning info if you updated from 7.9 to 8.4 as network.service used",
        "branch": "rhel",
        "status": "active",
        "link": "",
        "path": "journal, dmesg",
        "trigger": ""
    },
    "msg_87": {
        "content": "GPT: Use GNU Parted to correct GPT errors.",
        "analyze": "this is information only when launch instance with bigger disk size",
        "branch": "rhel",
        "status": "active",
        "link": "",
        "path": "journal, dmesg",
        "trigger": ""
    },
    "msg_88": {
        "content": "sshd.*: Invalid user .* from .* port .*.;sshd.*:.*authentication.*;sshd.*:.*Failed password.*",
        "analyze": "this is information only when invalid user login",
        "branch": "rhel",
        "status": "active",
        "link": "",
        "path": "journal, dmesg",
        "trigger": ""
    },
    "msg_89": {
        "content": "sshd.* banner exchange: Connection from .* port .*: invalid format;sshd.*: error: kex_exchange_identification: client sent invalid protocol identifier.*",
        "analyze": "this is information only when invalid user login",
        "branch": "rhel",
        "status": "active",
        "link": "",
        "path": "journal, dmesg",
        "trigger": ""
    },
    "msg_90": {
        "content": "[drm] psp command (0xD) failed and response status is (0x80000204)",
        "analyze": "this is information only while amdgpu is not supported in rhel",
        "branch": "rhel",
        "status": "active",
        "link": "https://bugzilla.redhat.com/show_bug.cgi?id=1969797",
        "path": "journal, dmesg",
        "trigger": "amdgpu"
    },
    "msg_91": {
        "content": "modprobe: ERROR: could not insert .*: No such device",
        "analyze": "this is information only and the messages can be safely disregardedl",
        "branch": "rhel",
        "status": "active",
        "link": "https://access.redhat.com/solutions/2853221",
        "path": "journal, dmesg",
        "trigger": "fips mode: enabled"
    },
    "msg_92": {
        "content": "usr/lib/modules/.*/kernel/.*net.*failover.ko.xz",
        "analyze": "this is a mode name only",
        "branch": "rhel",
        "status": "active",
        "link": "",
        "path": "journal, dmesg",
        "trigger": ""
    },
    "msg_93": {
        "content": "/usr/sbin/irqbalance[756]: libcap-ng used by \"/usr/sbin/irqbalance\" failed due to not having CAP_SETPCAP in capng_apply",
        "analyze": "Known issue",
        "branch": "rhel",
        "status": "active",
        "link": "https://bugzilla.redhat.com/show_bug.cgi?id=1963152",
        "path": "journal, dmesg",
        "trigger": ""
    },
    "msg_94": {
        "content": "audit: CONFIG_CHANGE op=set audit_failure=1 old=1 auid=4294967295 ses=4294967295 subj=system_u:system_r:unconfined_service_t:s0 res=1",
        "analyze": "this is info of login",
        "branch": "rhel",
        "status": "active",
        "link": "",
        "path": "journal, dmesg",
        "trigger": ""
    },
    "msg_95": {
        "content": "pstore: crypto_comp_decompress failed, ret = -22!",
        "analyze": "this is know issue and can ignore it, user also can avoid by clean up /sys/fs/pstore",
        "branch": "rhel",
        "status": "active",
        "link": "https://bugzilla.redhat.com/show_bug.cgi?id=1978938, https://bugzilla.redhat.com/show_bug.cgi?id=1993551#c16",
        "path": "journal, dmesg",
        "trigger": ""
    },
    "msg_96": {
        "content": "pstore: decompression failed: -22",
        "analyze": "this is know issue and can ignore it, user also can avoid by clean up /sys/fs/pstore",
        "branch": "rhel",
        "status": "active",
        "link": "https://bugzilla.redhat.com/show_bug.cgi?id=1978938, https://bugzilla.redhat.com/show_bug.cgi?id=1993551#c16",
        "path": "journal, dmesg",
        "trigger": ""
    },
    "msg_97": {
        "content": ".*kernel: system .*: [mem .*] could not be reserved.*",
        "analyze": "this is information level message and harmless if no functional impaction",
        "branch": "rhel",
        "status": "active",
        "link": "",
        "path": "journal, dmesg",
        "trigger": ""
    },
    "msg_98": {
        "content": "rngd.* Initialization Failed",
        "analyze": "rhel8.3+ do not require rng-tools any more(rhbz#1888695) and not all system supports hwrng and rdrand.",
        "branch": "rhel",
        "status": "active",
        "link": "https://ask.fedoraproject.org/t/rngd-entropy-generation-is-slow-consider-tuning-adding-sources/11720/3",
        "path": "journal, dmesg",
        "trigger": ""
    },
    "msg_99": {
        "content": ".*COMMAND=/bin/rpm -V.*",
        "analyze": "some pkg has error keywords when run test_check_rpm_V cases, ignore it",
        "branch": "rhel",
        "status": "active",
        "link": "",
        "path": "journal, dmesg",
        "trigger": ""
    },
    "msg_100": {
        "content": "microcode_ctl: kernel version .* failed early load check for .*, skipping",
        "analyze": "The message can be ignored.",
        "branch": "rhel",
        "status": "active",
        "link": "https://access.redhat.com/solutions/4388631",
        "path": "journal, dmesg",
        "trigger": ""
    },
    "msg_101": {
        "content": "ctstate INVALID,NEW",
        "analyze": "iptables output 'iptables -L -v -n'",
        "branch": "rhel",
        "status": "active",
        "link": "",
        "path": "journal, dmesg",
        "trigger": ""
    },
    "msg_102": {
        "content": "INFO Daemon Daemon WireServer endpoint is not found. Rerun dhcp handler",
        "analyze": "information only on azure",
        "branch": "rhel",
        "status": "active",
        "link": "",
        "path": "journal, dmesg",
        "trigger": ""
    },
    "msg_103": {
        "content": ".*dracut module.* will not be installed, because command .* could not be found!.*;.*dracut.*Could not find any command of.*",
        "analyze": "These warnings are safe to be ignored.",
        "branch": "rhel",
        "status": "active",
        "link": "https://access.redhat.com/solutions/3683511",
        "path": "journal, dmesg",
        "trigger": ""
    },
    "msg_104": {
        "content": ".*kernel: print_req_error: .* callbacks suppressed.*",
        "analyze": "information only",
        "branch": "rhel",
        "status": "active",
        "link": "",
        "path": "journal, dmesg",
        "trigger": ""
    },
    "msg_105": {
        "content": ".*Unknown command line parameters: BOOT_IMAGE.*64$;.*Unknown kernel.* \"BOOT_IMAGE=.*64\", will be passed to user space.$;.*dracut-cmdline.*: Invalid command.*",
        "analyze": "BOOT_IMAGE is a know unknow command line parameters",
        "branch": "rhel",
        "status": "active",
        "link": "https://lore.kernel.org/all/20210511211009.42259-1-ahalaney@redhat.com/T/#u",
        "path": "journal, dmesg",
        "trigger": "BOOT_IMAGE"
    },
    "msg_106": {
        "content": ".*xHCI BIOS handoff failed.*",
        "analyze": "Not the RHEL problem, mostly like bios disable USB function, check with vendor if you wish. skip on amazon",
        "branch": "rhel",
        "status": "active",
        "link": "https://bugzilla.redhat.com/show_bug.cgi?id=2018397",
        "path": "journal, dmesg",
        "trigger": "AMAZON"
    },
    "msg_107": {
        "content": ".*Unexpected SPCR Access Width.*",
        "analyze": "Expected behavior in amazon platform and no functional impact.",
        "branch": "rhel",
        "status": "active",
        "link": "https://bugzilla.redhat.com/show_bug.cgi?id=2018429",
        "path": "journal, dmesg",
        "trigger": "AMAZON"
    },
    "msg_108": {
        "content": ".*Hibernation image not present or could not be loaded.*",
        "analyze": "Because of hibernation partition on the hypervisor is not populated.",
        "branch": "rhel-7.9",
        "status": "active",
        "link": "https://bugzilla.redhat.com/show_bug.cgi?id=2018933,https://bugzilla.redhat.com/show_bug.cgi?id=2019530",
        "path": "journal, dmesg",
        "trigger": "el7"
    },
    "msg_109": {
        "content": ".*Could not set AlternativeName.*File exists.*;.*Could not apply link config.*File exists.*",
        "analyze": "Known issue in RHEL-8.5",
        "branch": "rhel-8.5",
        "status": "active",
        "link": "https://bugzilla.redhat.com/show_bug.cgi?id=2022432",
        "path": "journal, dmesg",
        "trigger": "el8"
    },
    "msg_110": {
        "content": ".*mtrr_cleanup: can not find optimal value.*;.*BAD*gran_size.*",
        "analyze": "there is similar explaination in ks file, try attach 'cat /proc/mtrr' if you want a bz",
        "branch": "rhel",
        "status": "active",
        "link": "https://access.redhat.com/solutions/87433",
        "path": "journal, dmesg",
        "trigger": "metal"
    },
    "msg_111": {
        "content": ".*ftrace: allocat.*;.*Mount.*Kernel Trace File System.*",
        "analyze": "this is not a real trace back",
        "branch": "rhel",
        "status": "active",
        "link": "",
        "path": "journal, dmesg",
        "trigger": ""
    },
    "msg_112": {
        "content": ".*SpeculationIndirectBranch:.*unknown.*",
        "analyze": "SpeculationIndirectBranch status unknow under proc in arm, same in upstream too",
        "branch": "rhel",
        "status": "active",
        "link": "",
        "path": "/proc/self/status",
        "trigger": "aarch64"
    },
    "msg_113": {
        "content": ".*trace event string verifier disabled.*",
        "analyze": "information only started from rhel-9",
        "branch": "rhel",
        "status": "active",
        "link": "",
        "path": "journal, dmesg",
        "trigger": "aarch64"
    },
    "msg_114": {
        "content": ".*Could not find 'strip'. Not stripping the initramfs.*",
        "analyze": "warning information only",
        "branch": "rhel",
        "status": "active",
        "link": "https://bugzilla.redhat.com/show_bug.cgi?id=867829",
        "path": "journal, dmesg",
        "trigger": ""
    },
    "msg_115": {
        "content": ".*imjournal: No statefile exists.*",
        "analyze": "can be ignored if system first boot",
        "branch": "rhel",
        "status": "active",
        "link": "",
        "path": "journal, dmesg",
        "trigger": ""
    },
    "msg_116": {
        "content": ".*x86/split lock detection: disabled.*",
	"analyze": "Debug kernel only. This https://elixir.bootlin.com/linux/latest/source/arch/x86/kernel/cpu/intel.c#L1273 is the function that does the reporting of the split lock detection feature. Linux's default setting for split lock detection is off, see https://elixir.bootlin.com/linux/latest/source/arch/x86/kernel/cpu/intel.c#L53. Hence, the message is expected. Also, this cannot appear on gen5 and gen4 (i3.metal) since the feature isn't available there.",
        "branch": "rhel",
        "status": "active",
        "link": "https://bugzilla.redhat.com/show_bug.cgi?id=2017161#c17",
        "path": "journal, dmesg",
        "trigger": "metal"
    },
    "msg_117": {
        "content": ".*Could not generate persistent MAC address for.*No such file or directory.*",
        "analyze": "known issue in rhel8 about veth interface",
        "branch": "rhel",
        "status": "active",
        "link": "https://bugzilla.redhat.com/show_bug.cgi?id=2026544",
        "path": "journal, dmesg",
        "trigger": ""
    },
    "msg_118": {
        "content": ".*iommu: DMA domain TLB invalidation policy: lazy mode.*",
        "analyze": "known log if iommu.strict=0 used in boot or x86 system",
        "branch": "rhel",
        "status": "active",
        "link": "https://bugzilla.redhat.com/show_bug.cgi?id=1836058",
        "path": "journal, dmesg",
        "trigger": ""
    },
    "msg_119": {
        "content": ".*rh-cloud-firstboot.*action: command not found.*",
        "analyze": "missing initscripts pkg",
        "branch": "rhel",
        "status": "active",
        "link": "https://bugzilla.redhat.com/show_bug.cgi?id=2027233",
        "path": "journal, dmesg",
        "trigger": ""
    },
    "msg_120": {
        "content": ".*traps: umip_basic_test.* general protection fault ip.*",
        "analyze": "information only produced by ltp",
        "branch": "rhel",
        "status": "active",
        "link": "",
        "path": "journal, dmesg",
        "trigger": ""
    },
    "msg_121": {
        "content": ".*lock detection:.*crashing the kernel on kernel split_locks and warning.*",
        "analyze": "information only",
        "branch": "rhel",
        "status": "active",
        "link": "https://lore.kernel.org/all/20210322135325.682257-3-fenghua.yu@intel.com/",
        "path": "journal, dmesg",
        "trigger": ""
    },
    "msg_122": {
        "content": ".*Unable to open /dev/kvm: No such file or directory.*",
        "analyze": "information only",
        "branch": "rhel",
        "status": "active",
        "link": "https://access.redhat.com/solutions/4621651",
        "path": "journal, dmesg",
        "trigger": ""
    },
    "msg_123": {
        "content": ".*Driver has suspect GRO implementation, TCP performance may be compromised.*",
        "analyze": "informational only and as a warning one which may be safely ignored",
        "branch": "rhel",
        "status": "active",
        "link": "https://access.redhat.com/solutions/3152971",
        "path": "journal, dmesg",
        "trigger": ""
    },
    "msg_124": {
        "content": ".*pci_bus 0000:00: Unknown NUMA node; performance will be reduced.*",
        "analyze": "this is know information in aws, we care nvme, ena numa node here",
        "branch": "rhel",
        "status": "active",
        "link": "https://bugzilla.redhat.com/show_bug.cgi?id=2037069#c17",
        "path": "journal, dmesg",
        "trigger": "AMAZON"
    },
    "msg_125": {
        "content": ".*systemd-sysctl.* Couldn't write '1' to 'vm/unprivileged_userfaultfd', ignoring: No such file or directory.*",
        "analyze": "The error message seen in the log is harmless and it's even marked as NOTICE",
        "branch": "rhel",
        "status": "active",
        "link": "https://bugzilla.redhat.com/show_bug.cgi?id=2051329",
        "path": "journal",
        "trigger": ""
    },
    "msg_126": {
        "content": ".*systemd-sysctl.* Couldn't write '0 2147483647' to '-net/ipv4/ping_group_range', ignoring: No such file or directory.*",
        "analyze": "this should be fixed in systemd-239-57.el8",
        "branch": "rhel",
        "status": "active",
        "link": "https://bugzilla.redhat.com/show_bug.cgi?id=2037807",
        "path": "journal",
        "trigger": ""
    },
    "msg_127": {
        "content": ".*systemd.* condition check.*",
        "analyze": "not a bug, conditions work behavior in systemd.unit(5)",
        "branch": "rhel",
        "status": "active",
        "link": "https://bugzilla.redhat.com/show_bug.cgi?id=2054986",
        "path": "journal",
        "trigger": ""
    },
    "msg_128": {
        "content": ".*Failed to insert 'ipmi_si': No such device.*;.*systemd-modules-load.service.*",
        "analyze": "will be fixed in fwupd-1.7.4-1.el8",
        "branch": "rhel",
        "status": "active",
        "link": "https://bugzilla.redhat.com/show_bug.cgi?id=2030993",
        "path": "dmesg,journal",
        "trigger": ""
    },
    "msg_129": {
        "content": ".*Couldn't stat device /dev/char/10:200: No such file or directory.*",
        "analyze": "generated when container run",
        "branch": "rhel",
        "status": "active",
        "link": "https://bugzilla.redhat.com/show_bug.cgi?id=1945929",
        "path": "dmesg,journal",
        "trigger": "Started libcontainer"
    },
    "msg_130": {
        "content": ".*nm-cloud-setup.service: Failed with result 'signal'.*",
        "analyze": "Info only, will trigger when NetworkManager restart",
        "branch": "rhel",
        "status": "active",
        "link": "",
        "path": "dmesg,journal",
        "trigger": "Reloading Network Manager"
    },
    "msg_131": {
        "content": ".*DataSourceGCE.py[WARNING]: address \"http://metadata.google.internal/computeMetadata/v1/\" is not resolvable.*",
        "analyze": "NetworkManager haven't update dns record when cloud-init use it.",
        "branch": "rhel8,rhel9",
        "status": "active",
        "link": "",
        "path": "journal",
        "trigger": ""
    },
    "msg_132": {
        "content": ".*Failed to find module 'ipmi-devintf'.*",
        "analyze": "fwupd contains modules-load.d which include this module but not exists in initramfs",
        "branch": "rhel9",
        "status": "active",
        "link": "https://bugzilla.redhat.com/show_bug.cgi?id=2092888",
        "path": "journal",
        "trigger": ""
    },
    "msg_133": {
        "content": ".*pam_motd(sshd:session): pam_motd: error scanning directory /run/motd.d.*",
        "analyze": "Existing bug",
        "branch": "rhel8",
        "status": "active",
        "link": "https://bugzilla.redhat.com/show_bug.cgi?id=2093495",
        "path": "journal",
        "trigger": ""
    },
    "msg_134": {
        "content": "Warning: Unmaintained hardware is detected:  e1000",
        "analyze": "e1000 is legacy",
        "branch": "rhel",
        "status": "active",
        "link": "",
        "path": "dmesg",
        "trigger": ""
    },
    "msg_135": {
        "content": "cloud-final.service: Main process exited, code=exited, status=2/INVALIDARGUMENT",
        "analyze": "Kernel cmdline contains 'console=ttyS0' in RHEL qcow2 image, but Nutanix AHV doesn't has serial console, which will caused cloud-final.service failed to start, then trigger this message",
        "branch": "rhel",
        "status": "active",
        "link": "https://bugzilla.redhat.com/show_bug.cgi?id=2034588",
        "path": "journal",
        "trigger": "ahv"
    },
    "msg_136": {
        "content": "cloud-final.service: Failed with result 'exit-code'.",
        "analyze": "Kernel cmdline contains 'console=ttyS0' in RHEL qcow2 image, but Nutanix AHV doesn't has serial console, which will caused cloud-final.service failed to start, then trigger this message",
        "branch": "rhel",
        "status": "active",
        "link": "https://bugzilla.redhat.com/show_bug.cgi?id=2034588",
        "path": "journal",
        "trigger": "ahv"
    },
    "msg_137": {
        "content": "cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)",
        "analyze": "Kernel cmdline contains 'console=ttyS0' in RHEL qcow2 image, but Nutanix AHV doesn't has serial console, which will caused cloud-final.service failed to start, then trigger this message",
        "branch": "rhel",
        "status": "active",
        "link": "https://bugzilla.redhat.com/show_bug.cgi?id=2034588",
        "path": "journal",
        "trigger": "ahv"
    },
    "msg_138": {
        "content": "util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_scripts_user.py'>) failed",
        "analyze": "Kernel cmdline contains 'console=ttyS0' in RHEL qcow2 image, but Nutanix AHV doesn't has serial console, which will caused cloud-final.service failed to start, then trigger this message",
        "branch": "rhel",
        "status": "active",
        "link": "https://bugzilla.redhat.com/show_bug.cgi?id=2034588",
        "path": "journal",
        "trigger": "ahv"
    },
    "msg_139": {
        "content": "util.py[WARNING]: Running module ssh-authkey-fingerprints (<module 'cloudinit.config.cc_ssh_authkey_fingerprints' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_ssh_authkey_fingerprints.py'>) failed",
        "analyze": "Kernel cmdline contains 'console=ttyS0' in RHEL qcow2 image, but Nutanix AHV doesn't has serial console, which will caused cloud-final.service failed to start, then trigger this message",
        "branch": "rhel",
        "status": "active",
        "link": "https://bugzilla.redhat.com/show_bug.cgi?id=2034588",
        "path": "journal",
        "trigger": "ahv"
    },
    "msg_140": {
        "content": "cc_keys_to_console.py[WARNING]: Writing keys to the system console failed!",
        "analyze": "Kernel cmdline contains 'console=ttyS0' in RHEL qcow2 image, but Nutanix AHV doesn't has serial console, which will caused cloud-final.service failed to start, then trigger this message",
        "branch": "rhel",
        "status": "active",
        "link": "https://bugzilla.redhat.com/show_bug.cgi?id=2034588",
        "path": "journal",
        "trigger": "ahv"
    },
    "msg_141": {
        "content": "util.py[WARNING]: Running module keys-to-console (<module 'cloudinit.config.cc_keys_to_console' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_keys_to_console.py'>) failed",
        "analyze": "Kernel cmdline contains 'console=ttyS0' in RHEL qcow2 image, but Nutanix AHV doesn't has serial console, which will caused cloud-final.service failed to start, then trigger this message",
        "branch": "rhel",
        "status": "active",
        "link": "https://bugzilla.redhat.com/show_bug.cgi?id=2034588",
        "path": "journal",
        "trigger": "ahv"
    },
    "msg_142": {
        "content": ".*data leaks possible.*",
        "analyze": "data leaks is expected as no microcode loaded in virtual system",
        "branch": "rhel",
        "status": "active",
        "link": "",
        "path": "dmesg",
        "trigger": "Hypervisor detected"
    }
}
